routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------
|*/

Route::get('/', 'FrontController@index')->name('front.index');

Route::get('/404', 'FrontController@notFound')->name('front.404');

Route::get('/curation', 'FrontController@curation')->name('front.curation');

Route::get('/curation/content-content', 'FrontController@curation')->name('front.curation-content');

Route::get('/curation-post/{id}', 'FrontController@curationPost')->name('front.curation-post');

Route::get('/capsule', 'FrontController@capsule')->name('front.capsule');

Route::get('/capsule-details/{id}', 'FrontController@capsuleDetails')->name('front.capsule-details');

Route::get('/service-terms', 'FrontController@serviceTerms')->name('front.service-terms');

Route::get('/privacy-policy', 'FrontController@privacyPolicy')->name('front.privacy-policy');

Route::get('/about-us', 'FrontController@aboutUs')->name('front.about-us');

Route::get('/business', 'FrontController@business')->name('front.business');


//Auth Routes
Route::group(['middleware' => ['auth']], function () {
    /*Like*/
    Route::post('/likes/post/', 'LikesController@like')->name('likes.like');
    Route::post('/likes/{id}', 'LikesController@dislike')->name('likes.dislike');


    /*Shopping Bag*/
    Route::get('/shopping-bag', 'FrontController@shoppingBag')->name('front.shopping-bag');
    Route::get('/add-shopping-bag/{id}', 'FrontController@addShoppingBag')->name('front.add-shopping-bag');
    Route::patch('update-shopping-bag', 'FrontController@updateShoppingBag');
    Route::delete('remove-shopping-bag', 'FrontController@removeShoppingBag');
    Route::get('/checkout-bag', 'FrontController@checkoutBag')->name('front.checkout-bag');
    Route::get('/place-order/{id}', 'FrontController@placeOrder')->name('front.place-order');
    Route::get('/place-order/mail', 'FrontController@placeOrderMail')->name('front.order-mail');
    Route::get('/order-details', 'FrontController@orderDetails')->name('front.order-details');
    Route::get('/continue-shopping', 'FrontController@continueShopping')->name('front.continue-shopping');
    Route::get('/track-order', 'FrontController@trackOrder')->name('front.track-order');

    Route::get('/shopping-closet', 'ShoppingClosetsController@shoppingCloset')->name('front.shopping-closet');

    Route::get('/shopping-closet/{id}', 'ShoppingClosetsController@updateCustomer')->name('front.update-customer');

    Route::post('/my-profile/{id}', 'ShoppingClosetsController@myProfile')->name('front.my-profile');

    Route::get('/contact-us', 'FrontController@contactUs')->name('front.contact-us');

    Route::get('/support', 'FrontController@support')->name('front.support');
});


/*Facebook login*/
Route::get('login/facebook', 'Auth\LoginController@redirectToProviderFacebook')->name('login.facebook');
Route::get('facebook/callback', 'Auth\LoginController@handleProviderCallbackFacebook');

/*Twitter login*/
Route::get('login/twitter', 'Auth\LoginController@redirectToProviderTwitter')->name('login.twitter');
Route::get('twitter/callback', 'Auth\LoginController@handleProviderCallbackTwitter');

/*Google login*/
Route::get('login/google', 'Auth\LoginController@redirectToProviderGoogle')->name('login.google');
Route::get('auth/google/callback', 'Auth\LoginController@handleProviderCallbackGoogle');


/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
|*/

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth', 'dashboard-access']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/profile', 'DashboardController@myProfile')->name('dashboard.profile');

    /*Curation Colors*/
    Route::resource('/colors', 'CurationColorsController');

    /* Curation Categories*/

    Route::get('/categories/index', 'CurationCategoriesController@index')->name('curation-categories.index');
    Route::get('/add-category', 'CurationCategoriesController@addCategory')->name('curation-categories.add-category');
    Route::get('/edit-category/{id}', 'CurationCategoriesController@editCategory')->name('curation-categories.edit-category');
    Route::get('/store-category', 'CurationCategoriesController@store')->name('curation-categories.store-category');
    Route::get('/delete-category/{id}', 'CurationCategoriesController@deleteCategory')->name('curation-categories.delete-category');

    /*Curation list*/
    Route::resource('/curation-lists', 'CurationListsController');

    /*Curation Types*/
    Route::resource('/curation-types', 'CurationTypesController');

    /*Capsule Brands*/
    Route::resource('/capsule-brands', 'CapsuleBrandsController');

    /*Capsule Sizes*/
    Route::resource('/capsule-sizes', 'CapsuleSizesController');

    /*Capsule Lists*/
    Route::resource('/capsule-lists', 'CapsuleListsController');

    Route::patch('/capsule-lists/{id}/edit', 'CapsuleListsController@addGallery')->name('capsule-list.add-gallery');
    Route::post('/capsule-lists/{id}/delete-gallery', 'CapsuleListsController@deleteGallery')->name('capsule-list.delete-gallery');


    /*Home Curations*/
    Route::resource('/home-curations', 'HomeCurationsController');

    /*Orders*/
    Route::resource('/orders', 'OrdersController');

    /*Merchants*/
    Route::resource('/merchants', 'MerchantsController');
    Route::post('/merchants/{id}', 'MerchantsController@deleteImage')->name('merchants.delete-image');

    /*Home Capsules*/
    Route::resource('/home-capsules', 'HomeCapsulesController');
    Route::post('/home-capsules/{id}', 'HomeCapsulesController@deleteImage')->name('home-capsules.delete-image');

    /*Website Content*/
    Route::get('/website-contents/terms-content', 'WebsiteContentsController@termsContent')->name('website-contents.terms-content');
    Route::post('/website-contents/terms-content/create', 'WebsiteContentsController@termsCreate')->name('website-contents.terms-create');

    Route::get('/website-contents/privacy-content', 'WebsiteContentsController@privacyContent')->name('website-contents.privacy-content');
    Route::post('/website-contents/privacy-content/create', 'WebsiteContentsController@privacyCreate')->name('website-contents.privacy-create');

    Route::get('/website-contents/about-content', 'WebsiteContentsController@aboutContent')->name('website-contents.about-content');
    Route::post('/website-contents/about-content/create', 'WebsiteContentsController@aboutCreate')->name('website-contents.about-create');

    Route::get('/website-contents/contact-content', 'WebsiteContentsController@contactContent')->name('website-contents.contact-content');
    Route::post('/website-contents/contact-content/create', 'WebsiteContentsController@contactCreate')->name('website-contents.contact-create');

    Route::get('/website-contents/support-content', 'WebsiteContentsController@supportContent')->name('website-contents.support-content');
    Route::post('/website-contents/support-content/create', 'WebsiteContentsController@supportCreate')->name('website-contents.support-create');

    Route::get('/website-contents/business-content', 'WebsiteContentsController@businessContent')->name('website-contents.business-content');
    Route::post('/website-contents/business-content/create', 'WebsiteContentsController@businessCreate')->name('website-contents.business-create');


    /*Manage Users*/
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::post('/users/{id}', 'UsersController@updateMyProfile')->name('users.update-my-profile');
    Route::get('/users/edit-user/{id}', 'UsersController@editUser')->name('users.edit-user');
    Route::post('/users/{id}/update-user', 'UsersController@updateUser')->name('users.update-user');
    Route::get('/users/{id}/delete-user', 'UsersController@deleteUser')->name('users.delete-user');

});


Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Route::get('/updateapp', function () {
    \Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});

app/HomeCapsule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HomeCapsule extends Model
{
    protected $fillable = ['description'];
}

app/Http/Controllers/HomeCapsulesController.php
<?php

namespace App\Http\Controllers;

use App\HomeCapsule;
use App\Upload;
use Illuminate\Http\Request;
use File;

class HomeCapsulesController extends Controller
{
    public function index()
    {

        $details = HomeCapsule::all();

        $images = Upload::where('type', '=', 'home_capsule')->get();

        return view('home-capsules.index', compact('details', 'images'));
    }

    public function store(Request $request)
    {

        $request->validate([
            'description' => 'required'
        ]);

        $input = $request->all();

        $contentAvailable = HomeCapsule::count();
        $updateFirstRaw = HomeCapsule::first();

        if($contentAvailable > 0){

            $updateFirstRaw->update($input);

        }else{

            HomeCapsule::create($input);
        }

        return redirect(route('home-capsules.index'))->with('success', 'Home Capsule Content Has Been Added');

    }

    public function update(Request $request)
    {
        {
            //dd($request->all());
            $image = $request->file('file');
            $fileName = $image->getClientOriginalName();
            $image->move(public_path('/assets/images/capsule-featured/'),$fileName);

            $fileUpload = new Upload();
            $fileUpload->file = $fileName;
            $fileUpload->file_id = $request->get('file_id');
            $fileUpload->type = $request->get('type');
            $fileUpload->save();
            //return response()->json(['success'=>$fileName]);
            return redirect(route('home-capsules.index'))->with('success', 'Home Capsule Image Uploaded!');
        }
    }

    public function destroy($id)
    {
        $input = HomeCapsule::findOrFail($id);

        $deleteFile = Upload::findorFail($id);

        $fileName = $deleteFile->file_id;

        if(File::exists(public_path('/assets/images/capsule-featured/') . $fileName)){
            unlink(public_path('/assets/images/capsule-featured/') . $fileName);
        }

        $input->delete();

        return redirect(route('home-capsules.index'))->with('success', 'Home Capsule Content Has Been Deleted!');
    }

    public function deleteImage($id)
    {
        $input = Upload::findOrFail($id);

        $fileName = $input->file;

        if(File::exists(public_path('assets/images/capsule-featured/') . $fileName)){
            unlink(public_path('assets/images/capsule-featured/') . $fileName);
        }
        $input->delete();

        return redirect(route('home-capsules.index'))->with('success', 'Image Deleted');
    }


}

resources/views/home-capsules/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Home Capsule')

@section('additional-css')

    <link href="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/select2/select2.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/multiselect/multi-select.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/flatpickr/flatpickr.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.css') }}" rel="stylesheet"/>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css" rel="stylesheet" />
    <link href="{{ asset('/dassets/libs/summernote/summernote-bs4.css') }}" rel="stylesheet"/>

@endSection()



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Products</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Home Capsule</h4>
                    </div>
                </div>
                @include('layouts.includes.success')
                @include('layouts.includes.errors')


                <div class="row">

                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{ route('home-capsules.store') }}" method="post"
                                      enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    <div class="form-group row">
                                        <label class="col-lg-12 col-form-label" for="description">Description</label>
                                        <div class="col-lg-12">
                                            <textarea class="form-control" rows="5" name="description"></textarea>
                                        </div>
                                    </div>
                                    <button class="btn btn-block btn--md btn-primary" type="submit">Add Home Capsule
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                @if($details->toArray())

                                    @foreach($details as $detail)
                                        <div class="col-lg-12 col-xl-12">
                                            <p>{{ $detail->description }}</p>
                                        </div>

                                    @endforeach
                                      <hr>

                                        <button type="button" class="btn btn-secondary btn-block" data-toggle="modal" data-target="#upload">Upload Images</button>

                                    </div>
                                @else
                                    <div class="col-lg-12 col-xl-12">
                                        <p class="text-center">Please add <strong>Capsule Featured</strong> for home
                                            page.</p>
                                        <hr/>
                                    </div>

                                @endif


                            </div>

                        </div>
                        <div class="row">

                        </div>


                    </div>


                </div>

                <div class="row">
                    @if($images->toArray())
                        @foreach($images as $image)
                    <div class="card mb-3 mb-xl-0">
                        <img class="card-img-top img-fluid" src="{{ asset('assets/images/capsule-featured/' . $image->file ) }}" alt="" style="max-width: 400px;">
                        <div class="card-body">
                            <form action="{{ route('home-capsules.delete-image',$image->id) }}" method="POST">
                                @csrf
                                <input type="submit" class="btn btn-danger btn-block" value="Delete"/>
                            </form>
                        </div>
                    </div>
                     @endforeach
                    @endif
                </div>

            </div> <!-- content -->

            @include('.home-capsules.modals')

            @endSection


            @section('additional-js')
                <script src="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
                <script src="{{ asset('/dassets/libs/select2/select2.min.js') }}"></script>
                <script src="{{ asset('/dassets/libs/multiselect/jquery.multi-select.js') }}"></script>
                <script src="{{ asset('/dassets/libs/flatpickr/flatpickr.min.js') }}"></script>
                <script src="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') }}"></script>
                <script src="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.js"></script>
                <script src="{{ asset('/dassets/js/pages/form-advanced.init.js') }}"></script>
                <script src="{{ asset('/dassets/libs/summernote/summernote-bs4.min.js') }}"></script>
                <script src="{{ asset('dassets/js/pages/form-editor.init.js') }}"></script>

                <script type="text/javascript">
                    Dropzone.options.dropzone =
                        {
                            maxFilesize: 10,
                            renameFile: function (file) {
                                var dt = new Date();
                                var time = dt.getTime();
                                return time + file.name;
                            },
                            acceptedFiles: ".jpeg,.jpg,.png,.gif",
                            addRemoveLinks: true,
                            timeout: 60000,
                            success: function (file, response) {
                                console.log(response);
                            },
                            error: function (file, response) {
                                return true;
                            }
                        };
                </script>





@endSection

resources/views/home-capsules/modals.blade.php
<div class="modal fade" id="upload" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myExtraLargeModalLabel">Upload</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="{{ route('home-capsules.update', 1) }}" name="file" method="post" class="dropzone" id="fileUploads" enctype="multipart/form-data">

                    {{ csrf_field() }}

                    {{ method_field('PATCH') }}

                    <input type="hidden" name="file_id" value="1">
                    <input type="hidden" name="type" value="home_capsule">
                    <div class="fallback">
                        <input name="file" type="file"  id="file" multiple />
                    </div>

                    <div class="dz-message needsclick">
                        <i class="h1 text-muted  uil-cloud-upload"></i>
                        <h3>Drop files here or click to upload.</h3>
                        <span class="text-muted font-13">(Please drop all <strong>Capsule</strong> images to display on home page.</span>
                    </div>
                </form>


            </div>
        </div>
    </div>
</div>