routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------
|*/

Route::get('/', 'FrontController@index')->name('front.index');

Route::get('/404', 'FrontController@notFound')->name('front.404');

Route::get('/curation', 'FrontController@curation')->name('front.curation');

Route::get('/curation/content-content', 'FrontController@curation')->name('front.curation-content');

Route::get('/curation-post/{id}', 'FrontController@curationPost')->name('front.curation-post');

Route::get('/capsule', 'FrontController@capsule')->name('front.capsule');

Route::get('/capsule-details/{id}', 'FrontController@capsuleDetails')->name('front.capsule-details');

Route::get('/service-terms', 'FrontController@serviceTerms')->name('front.service-terms');

Route::get('/privacy-policy', 'FrontController@privacyPolicy')->name('front.privacy-policy');

Route::get('/about-us', 'FrontController@aboutUs')->name('front.about-us');

Route::get('/business', 'FrontController@business')->name('front.business');


//Auth Routes
Route::group(['middleware' => ['auth']], function () {
    /*Like*/
    Route::post('/likes/post/', 'LikesController@like')->name('likes.like');
    Route::post('/likes/{id}', 'LikesController@dislike')->name('likes.dislike');


    /*Shopping Bag*/
    Route::get('/shopping-bag', 'FrontController@shoppingBag')->name('front.shopping-bag');
    Route::get('/add-shopping-bag/{id}', 'FrontController@addShoppingBag')->name('front.add-shopping-bag');
    Route::patch('update-shopping-bag', 'FrontController@updateShoppingBag');
    Route::delete('remove-shopping-bag', 'FrontController@removeShoppingBag');
    Route::get('/checkout-bag', 'FrontController@checkoutBag')->name('front.checkout-bag');
    Route::get('/place-order/{id}', 'FrontController@placeOrder')->name('front.place-order');
    Route::get('/place-order/mail', 'FrontController@placeOrderMail')->name('front.order-mail');
    Route::get('/order-details', 'FrontController@orderDetails')->name('front.order-details');
    Route::get('/continue-shopping', 'FrontController@continueShopping')->name('front.continue-shopping');
    Route::get('/track-order', 'FrontController@trackOrder')->name('front.track-order');

    Route::get('/shopping-closet', 'ShoppingClosetsController@shoppingCloset')->name('front.shopping-closet');

    Route::get('/shopping-closet/{id}', 'ShoppingClosetsController@updateCustomer')->name('front.update-customer');

    Route::post('/my-profile/{id}', 'ShoppingClosetsController@myProfile')->name('front.my-profile');

    Route::get('/contact-us', 'FrontController@contactUs')->name('front.contact-us');

    Route::get('/support', 'FrontController@support')->name('front.support');
});


/*Facebook login*/
Route::get('login/facebook', 'Auth\LoginController@redirectToProviderFacebook')->name('login.facebook');
Route::get('facebook/callback', 'Auth\LoginController@handleProviderCallbackFacebook');

/*Twitter login*/
Route::get('login/twitter', 'Auth\LoginController@redirectToProviderTwitter')->name('login.twitter');
Route::get('twitter/callback', 'Auth\LoginController@handleProviderCallbackTwitter');

/*Google login*/
Route::get('login/google', 'Auth\LoginController@redirectToProviderGoogle')->name('login.google');
Route::get('auth/google/callback', 'Auth\LoginController@handleProviderCallbackGoogle');


/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
|*/

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth', 'dashboard-access']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/profile', 'DashboardController@myProfile')->name('dashboard.profile');

    /*Curation Colors*/
    Route::resource('/colors', 'CurationColorsController');

    /* Curation Categories*/

    Route::get('/categories/index', 'CurationCategoriesController@index')->name('curation-categories.index');
    Route::get('/add-category', 'CurationCategoriesController@addCategory')->name('curation-categories.add-category');
    Route::get('/edit-category/{id}', 'CurationCategoriesController@editCategory')->name('curation-categories.edit-category');
    Route::get('/store-category', 'CurationCategoriesController@store')->name('curation-categories.store-category');
    Route::get('/delete-category/{id}', 'CurationCategoriesController@deleteCategory')->name('curation-categories.delete-category');

    /*Curation list*/
    Route::resource('/curation-lists', 'CurationListsController');

    /*Curation Types*/
    Route::resource('/curation-types', 'CurationTypesController');

    /*Capsule Brands*/
    Route::resource('/capsule-brands', 'CapsuleBrandsController');

    /*Capsule Sizes*/
    Route::resource('/capsule-sizes', 'CapsuleSizesController');

    /*Capsule Lists*/
    Route::resource('/capsule-lists', 'CapsuleListsController');

    Route::patch('/capsule-lists/{id}/edit', 'CapsuleListsController@addGallery')->name('capsule-list.add-gallery');
    Route::post('/capsule-lists/{id}/delete-gallery', 'CapsuleListsController@deleteGallery')->name('capsule-list.delete-gallery');


    /*Home Curations*/
    Route::resource('/home-curations', 'HomeCurationsController');

    /*Orders*/
    Route::resource('/orders', 'OrdersController');

    /*Merchants*/
    Route::resource('/merchants', 'MerchantsController');
    Route::post('/merchants/{id}', 'MerchantsController@deleteImage')->name('merchants.delete-image');

    /*Home Capsules*/
    Route::resource('/home-capsules', 'HomeCapsulesController');
    Route::post('/home-capsules/{id}', 'HomeCapsulesController@deleteImage')->name('home-capsules.delete-image');

    /*Website Content*/
    Route::get('/website-contents/terms-content', 'WebsiteContentsController@termsContent')->name('website-contents.terms-content');
    Route::post('/website-contents/terms-content/create', 'WebsiteContentsController@termsCreate')->name('website-contents.terms-create');

    Route::get('/website-contents/privacy-content', 'WebsiteContentsController@privacyContent')->name('website-contents.privacy-content');
    Route::post('/website-contents/privacy-content/create', 'WebsiteContentsController@privacyCreate')->name('website-contents.privacy-create');

    Route::get('/website-contents/about-content', 'WebsiteContentsController@aboutContent')->name('website-contents.about-content');
    Route::post('/website-contents/about-content/create', 'WebsiteContentsController@aboutCreate')->name('website-contents.about-create');

    Route::get('/website-contents/contact-content', 'WebsiteContentsController@contactContent')->name('website-contents.contact-content');
    Route::post('/website-contents/contact-content/create', 'WebsiteContentsController@contactCreate')->name('website-contents.contact-create');

    Route::get('/website-contents/support-content', 'WebsiteContentsController@supportContent')->name('website-contents.support-content');
    Route::post('/website-contents/support-content/create', 'WebsiteContentsController@supportCreate')->name('website-contents.support-create');

    Route::get('/website-contents/business-content', 'WebsiteContentsController@businessContent')->name('website-contents.business-content');
    Route::post('/website-contents/business-content/create', 'WebsiteContentsController@businessCreate')->name('website-contents.business-create');


    /*Manage Users*/
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::post('/users/{id}', 'UsersController@updateMyProfile')->name('users.update-my-profile');
    Route::get('/users/edit-user/{id}', 'UsersController@editUser')->name('users.edit-user');
    Route::post('/users/{id}/update-user', 'UsersController@updateUser')->name('users.update-user');
    Route::get('/users/{id}/delete-user', 'UsersController@deleteUser')->name('users.delete-user');

});


Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Route::get('/updateapp', function () {
    \Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});

app/CurationList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CurationList extends Model
{
    protected  $fillable = [

        'title',
        'description',
        'file',
        'links',
        'category_id',
        'type_id',
        'color_id',
        'is_active'
    ];

    public function category(){
        return $this->belongsTo('App\CurationCategory')->withDefault();
    }

    public function color(){
        return $this->belongsTo('App\CurationColor')->withDefault();
    }

    public function type(){
        return $this->belongsTo('App\CurationType')->withDefault();
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/CurationListsController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\CurationCreateRequest;
use App\Http\Requests\CurationUpdateRequest;
use Illuminate\Http\Request;
use File;

use App \ {CurationList, CurationCategory, CurationColor, CurationType};

class CurationListsController extends Controller
{

    public function index()
    {
     $curationLists = CurationList::all();
     return view ('curation-lists.index', compact('curationLists'));
    }


    public function create()
    {
        $categories = CurationCategory::all();
        $colors = CurationColor::all();
        $types = CurationType::all();
        //dd($categories);

        return view('curation-lists.create', compact('categories', 'colors', 'types'));
    }


    public function store(CurationCreateRequest $request)
    {
        $input = $request->all();

        if($file = $request->file('file')){
            $fileName = strtolower( time() . '_' . $file->getClientOriginalName());;

            $file->move(public_path('assets/images/curation/'),$fileName);

            $input['file'] = $fileName;
         }

       CurationList::create($input);

      return redirect(route('curation-lists.create'))->with('success', 'Curation Has Been Added');

    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $curation = CurationList::findOrFail($id);
        $categories = CurationCategory::all();
        $colors = CurationColor::all();
        $types = CurationType::all();
        return view('curation-lists.edit', compact('curation', 'categories', 'colors', 'types'));
    }


    public function update(CurationUpdateRequest $request, $id)
    {

        $input = $request->all();

        $curation = CurationList::findorfail($id);

        if($file = $request->file('file')){
            $fileName = strtolower( time() . '_' . $file->getClientOriginalName());;

            $file->move(public_path('assets/images/curation/'),$fileName);

            $input['file'] = $fileName;
        }

        $curation->update($input);

        return redirect(route('curation-lists.index'))->with('success', 'Curation Has Been Updated');
    }


    public function destroy($id)
    {
        $input = CurationList::findOrFail($id);

        $fileName = $input->file;

        if(File::exists(public_path('assets/images/curation/') . $fileName)){
            unlink(public_path('assets/images/curation/') . $fileName);
        }


        $input->delete();

        return redirect(route('curation-categories.index'))->with('success', 'Curation Has Been Deleted!');
    }
}

resources/views/curation-lists/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Add Curation')

@section('additional-css')

    <link href="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/select2/select2.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/multiselect/multi-select.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/flatpickr/flatpickr.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.css') }}" rel="stylesheet"/>

    <link href="{{ asset('/dassets/libs/dropzone/dropzone.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('/dassets/libs/summernote/summernote-bs4.css') }}" rel="stylesheet"/>

@endSection()



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Products</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Add Curation</h4>
                    </div>
                </div>
                @include('layouts.includes.success')
                @include('layouts.includes.errors')

                <form action="{{ route('curation-lists.store') }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-xl-4 col-sm-4">
                                            <div class="form-group mt-3 mt-sm-0">
                                                <label>Category</label>
                                                <select name="category_id" class="form-control">
                                                    <option value="" selected disabled hidden>Select Category</option>
                                                    @foreach($categories as $category)
                                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-xl-4 col-sm-4">
                                            <div class="form-group mt-3 mt-sm-0">
                                                <label>Type</label>
                                                <select name="type_id" class="form-control">
                                                    <option value="" selected disabled hidden>Select Type</option>
                                                    @foreach($types as $type)
                                                        <option value="{{ $type->id }}">{{ $type->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-xl-4 col-sm-4">
                                            <div class="form-group mt-3 mt-sm-0">
                                                <label>Colors Filter</label>

                                                <select name="color_id" class="form-control">
                                                    <option value="" selected disabled hidden>Select Color</option>
                                                    @foreach($colors as $color)
                                                        <option value="{{ $color->id }}"
                                                                style="background: {{$color->hex }}; color:#fff;">{{ $color->name }} </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                </div> <!-- end card-body -->
                            </div> <!-- end card-->
                        </div> <!-- end col -->
                    </div>
                    <div class="row">

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group row">
                                        <div class="col-lg-12">
                                            <input type="text" class="form-control" name="title" placeholder="Title">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-12 col-form-label" for="description">Description</label>
                                        <div class="col-lg-12">
                                            <textarea class="form-control" rows="5" name="description"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-12 col-form-label" for="links">Links</label>
                                        <textarea id="summernote-editor" name="links">
                                   <ul>
<li>STYLE ITEM 1 - R900 - <strong><a href="https://www.mrp.com" target="_blank">Mr Price</a></strong></li>
<li>STYLE ITEM 2 - R400 - <strong><a href="https://www.yoco.co.za" target="_blank">Tshepo</a></strong></li>
<li>STYLE ITEM 3 - R299 - <strong><a href="https://www.zara.com/za/" target="_blank">ZARA</a></strong></li>
</ul>
                                 </textarea>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-12 col-form-label" for="description">Active?</label>
                                        <div class="col-lg-12">
                                            <div class="">
                                                <div class="custom-control custom-radio mb-2">
                                                    <input type="radio" id="customRadio1" name="is_active"
                                                           class="custom-control-input" value="1" checked>
                                                    <label class="custom-control-label" for="customRadio1">Yes</label>
                                                </div>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" id="customRadio2" name="is_active"
                                                           class="custom-control-input" value="0">
                                                    <label class="custom-control-label" for="customRadio2">No</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="btn btn-block btn--md btn-primary" type="submit">Add Curation
                                    </button>

                                </div>
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="col-md-12">
                                        <label>Upload Curation Image <span style="color:red;">(440 X 660)</span></label>
                                        <input type="file" name="file"  class="form-control" />
                                    </div>

                                </div>

                            </div>


                        </div>
                </form>
            </div>

        </div> <!-- content -->

        @endSection


        @section('additional-js')
            <script src="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/select2/select2.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/multiselect/jquery.multi-select.js') }}"></script>
            <script src="{{ asset('/dassets/libs/flatpickr/flatpickr.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/dropzone/dropzone.min.js') }}"></script>
            <script src="{{ asset('/dassets/js/pages/form-advanced.init.js') }}"></script>
            <script src="{{ asset('/dassets/libs/summernote/summernote-bs4.min.js') }}"></script>
            <script src="{{ asset('dassets/js/pages/form-editor.init.js') }}"></script>


@endSection

resources/views/curation-lists/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Curation List')

@section('additional-css')
    <link href="{{ asset('/dassets/libs/datatables/dataTables.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/select.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />



@endSection()



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Curation List</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Curation List</h4>
                    </div>
                </div>


                <div class="row">
                    <div class="col-3">
                         <a href="{{ route('curation-lists.create') }}" class="btn btn-primary btn-block">Add New</a>
                        <br>
                    </div>

                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                              @if($curationLists->toArray())
                                <table id="basic-datatable" class="table dt-responsive nowrap">
                                    <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>File</th>
                                        <th>Color</th>
                                        <th>Type</th>
                                        <th>Category</th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    </thead>


                                    <tbody>
                                    @foreach($curationLists as $curation)
                                    <tr>
                                        <td>{{$curation->title }}</td>
                                        <td><img src="{{ asset('/assets/images/curation/' . $curation->file) }}" alt="{{$curation->title }}" class="img-fluid" style="max-width: 30px;" /> </td>
                                        <td class="text-center"><div style="width: 30px; height:30px; background: {{$curation->color->hex }}; border-radius:50%;"></div></td>
                                        <td>{{$curation->type->name }}</td>
                                        <td>{{$curation->category->name }}</td>
                                        <td class="text-center"> <a href="{{ route('curation-lists.edit', $curation->id) }}" class="btn btn-success btn-block">Edit</a></td>
                                        <td>
                                            <form action="{{url('curation-lists', [$curation->id])}}" method="POST">
                                                {{method_field('DELETE')}}
                                                @csrf
                                                <input type="submit" class="btn btn-danger btn-block" value="Delete"/>
                                            </form>
                                        </td>
                                    </tr>
                                     @endforeach
                                     </tbody>
                                </table>
                               @endif

                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->
                </div>

            </div>

        </div> <!-- content -->
    @endSection


    @section('additional-js')

        <!-- datatable js -->
            <script src="{{ asset('/dassets/libs/datatables/jquery.dataTables.min.js') }}"></script>
            <script src="{{ asset('dassets/libs/datatables/dataTables.bootstrap4.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/dataTables.responsive.min.js') }}"></script>
            <script src="{{ asset('/assets/libs/datatables/responsive.bootstrap4.min.js') }}"></script>

            <script src="{{ asset('/dassets/libs/datatables/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.bootstrap4.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.print.min.js') }}"></script>

            <script src="{{ asset('/dassets/libs/datatables/dataTables.keyTable.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/dataTables.select.min.js') }}"></script>



            <!-- Datatables init -->
            <script src="{{ asset('/dassets/js/pages/datatables.init.js') }}"></script>
            <script src="{{ asset('dassets/js/pages/form-advanced.init.js') }}"></script>

@endSection