routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------
|*/

Route::get('/', 'FrontController@index')->name('front.index');

Route::get('/404', 'FrontController@notFound')->name('front.404');

Route::get('/curation', 'FrontController@curation')->name('front.curation');

Route::get('/curation/content-content', 'FrontController@curation')->name('front.curation-content');

Route::get('/curation-post/{id}', 'FrontController@curationPost')->name('front.curation-post');

Route::get('/capsule', 'FrontController@capsule')->name('front.capsule');

Route::get('/capsule-details/{id}', 'FrontController@capsuleDetails')->name('front.capsule-details');

Route::get('/service-terms', 'FrontController@serviceTerms')->name('front.service-terms');

Route::get('/privacy-policy', 'FrontController@privacyPolicy')->name('front.privacy-policy');

Route::get('/about-us', 'FrontController@aboutUs')->name('front.about-us');

Route::get('/business', 'FrontController@business')->name('front.business');


//Auth Routes
Route::group(['middleware' => ['auth']], function () {
    /*Like*/
    Route::post('/likes/post/', 'LikesController@like')->name('likes.like');
    Route::post('/likes/{id}', 'LikesController@dislike')->name('likes.dislike');


    /*Shopping Bag*/
    Route::get('/shopping-bag', 'FrontController@shoppingBag')->name('front.shopping-bag');
    Route::get('/add-shopping-bag/{id}', 'FrontController@addShoppingBag')->name('front.add-shopping-bag');
    Route::patch('update-shopping-bag', 'FrontController@updateShoppingBag');
    Route::delete('remove-shopping-bag', 'FrontController@removeShoppingBag');
    Route::get('/checkout-bag', 'FrontController@checkoutBag')->name('front.checkout-bag');
    Route::get('/place-order/{id}', 'FrontController@placeOrder')->name('front.place-order');
    Route::get('/place-order/mail', 'FrontController@placeOrderMail')->name('front.order-mail');
    Route::get('/order-details', 'FrontController@orderDetails')->name('front.order-details');
    Route::get('/continue-shopping', 'FrontController@continueShopping')->name('front.continue-shopping');
    Route::get('/track-order', 'FrontController@trackOrder')->name('front.track-order');

    Route::get('/shopping-closet', 'ShoppingClosetsController@shoppingCloset')->name('front.shopping-closet');

    Route::get('/shopping-closet/{id}', 'ShoppingClosetsController@updateCustomer')->name('front.update-customer');

    Route::post('/my-profile/{id}', 'ShoppingClosetsController@myProfile')->name('front.my-profile');

    Route::get('/contact-us', 'FrontController@contactUs')->name('front.contact-us');

    Route::get('/support', 'FrontController@support')->name('front.support');
});


/*Facebook login*/
Route::get('login/facebook', 'Auth\LoginController@redirectToProviderFacebook')->name('login.facebook');
Route::get('facebook/callback', 'Auth\LoginController@handleProviderCallbackFacebook');

/*Twitter login*/
Route::get('login/twitter', 'Auth\LoginController@redirectToProviderTwitter')->name('login.twitter');
Route::get('twitter/callback', 'Auth\LoginController@handleProviderCallbackTwitter');

/*Google login*/
Route::get('login/google', 'Auth\LoginController@redirectToProviderGoogle')->name('login.google');
Route::get('auth/google/callback', 'Auth\LoginController@handleProviderCallbackGoogle');


/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
|*/

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth', 'dashboard-access']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('/profile', 'DashboardController@myProfile')->name('dashboard.profile');

    /*Curation Colors*/
    Route::resource('/colors', 'CurationColorsController');

    /* Curation Categories*/

    Route::get('/categories/index', 'CurationCategoriesController@index')->name('curation-categories.index');
    Route::get('/add-category', 'CurationCategoriesController@addCategory')->name('curation-categories.add-category');
    Route::get('/edit-category/{id}', 'CurationCategoriesController@editCategory')->name('curation-categories.edit-category');
    Route::get('/store-category', 'CurationCategoriesController@store')->name('curation-categories.store-category');
    Route::get('/delete-category/{id}', 'CurationCategoriesController@deleteCategory')->name('curation-categories.delete-category');

    /*Curation list*/
    Route::resource('/curation-lists', 'CurationListsController');

    /*Curation Types*/
    Route::resource('/curation-types', 'CurationTypesController');

    /*Capsule Brands*/
    Route::resource('/capsule-brands', 'CapsuleBrandsController');

    /*Capsule Sizes*/
    Route::resource('/capsule-sizes', 'CapsuleSizesController');

    /*Capsule Lists*/
    Route::resource('/capsule-lists', 'CapsuleListsController');

    Route::patch('/capsule-lists/{id}/edit', 'CapsuleListsController@addGallery')->name('capsule-list.add-gallery');
    Route::post('/capsule-lists/{id}/delete-gallery', 'CapsuleListsController@deleteGallery')->name('capsule-list.delete-gallery');


    /*Home Curations*/
    Route::resource('/home-curations', 'HomeCurationsController');

    /*Orders*/
    Route::resource('/orders', 'OrdersController');

    /*Merchants*/
    Route::resource('/merchants', 'MerchantsController');
    Route::post('/merchants/{id}', 'MerchantsController@deleteImage')->name('merchants.delete-image');

    /*Home Capsules*/
    Route::resource('/home-capsules', 'HomeCapsulesController');
    Route::post('/home-capsules/{id}', 'HomeCapsulesController@deleteImage')->name('home-capsules.delete-image');

    /*Website Content*/
    Route::get('/website-contents/terms-content', 'WebsiteContentsController@termsContent')->name('website-contents.terms-content');
    Route::post('/website-contents/terms-content/create', 'WebsiteContentsController@termsCreate')->name('website-contents.terms-create');

    Route::get('/website-contents/privacy-content', 'WebsiteContentsController@privacyContent')->name('website-contents.privacy-content');
    Route::post('/website-contents/privacy-content/create', 'WebsiteContentsController@privacyCreate')->name('website-contents.privacy-create');

    Route::get('/website-contents/about-content', 'WebsiteContentsController@aboutContent')->name('website-contents.about-content');
    Route::post('/website-contents/about-content/create', 'WebsiteContentsController@aboutCreate')->name('website-contents.about-create');

    Route::get('/website-contents/contact-content', 'WebsiteContentsController@contactContent')->name('website-contents.contact-content');
    Route::post('/website-contents/contact-content/create', 'WebsiteContentsController@contactCreate')->name('website-contents.contact-create');

    Route::get('/website-contents/support-content', 'WebsiteContentsController@supportContent')->name('website-contents.support-content');
    Route::post('/website-contents/support-content/create', 'WebsiteContentsController@supportCreate')->name('website-contents.support-create');

    Route::get('/website-contents/business-content', 'WebsiteContentsController@businessContent')->name('website-contents.business-content');
    Route::post('/website-contents/business-content/create', 'WebsiteContentsController@businessCreate')->name('website-contents.business-create');


    /*Manage Users*/
    Route::get('/users', 'UsersController@index')->name('users.index');
    Route::post('/users/{id}', 'UsersController@updateMyProfile')->name('users.update-my-profile');
    Route::get('/users/edit-user/{id}', 'UsersController@editUser')->name('users.edit-user');
    Route::post('/users/{id}/update-user', 'UsersController@updateUser')->name('users.update-user');
    Route::get('/users/{id}/delete-user', 'UsersController@deleteUser')->name('users.delete-user');

});


Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Route::get('/updateapp', function () {
    \Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['user_id','order_number', 'title',  'file',  'details','code', 'description','quantity', 'total','status', 'payment_method'];

    public function user(){
        return $this->belongsTo('App\User');
    }

    protected $primaryKey = "user_id";
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Order;

class OrdersController extends Controller
{

    public function index(){

        $orders = Order::get()->unique('order_number');

        return view('orders.index', compact('orders'));
    }

    public function show($id){

        $order = Order::where('order_number','=', $id)->get();

        //dd($order->toArray());

        $orderDetails = Order::where('order_number','=', $id)->get();

       return view('orders.show', compact('order', 'orderDetails'));


    }

    public function update(Request $request, $id){

        $input = $request->all();

        //$order = Order::where('order_number',$id)->first();
         Order::where('order_number', '=', $id)->update(array('status' => $request->status));


        //order->update($input);

        return redirect()->back()->with('success', 'Order Status Updated');
    }
}

resources/views/orders/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Manage Order')

@section('additional-css')
    <link href="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet"  type="text/css" />
    <link href="{{ asset('/dassets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('dassets/libs/multiselect/multi-select.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/flatpickr/flatpickr.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.css') }}" rel="stylesheet" type="text/css"/>
@endSection



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Update Order</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Manage Colors</h4>
                    </div>
                </div>
                @include('layouts.includes.success')
                @include('layouts.includes.errors')
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mt-0 mb-1">Update Order</h4>
                                <p class="sub-header"></p>
                                <form action="{{ route('capsule-lists.update', $capsule->id) }}" method="post">
                                    {{ csrf_field() }}

                                    {{ method_field('PATCH') }}

                                    <div class="form-group row">
                                        <label>Update Status</label>
                                        <select name="status" class="form-control">
                                            <option value="" selected disabled hidden>Status</option>
                                             <option>approved</option>
                                             <option>pending</option>
                                             <option>cancelled</option>
                                       </select>
                                     </div>

                                    <div class="form-group row">
                                        <div class="col-lg-6">
                                            <a href="#" class="btn btn-block btn--md btn-danger" onclick="goBack()">Cancel</a>
                                        </div>
                                        <div class="col-lg-6">
                                            <button class="btn btn-block btn--md btn-primary" type="submit">Update Order</button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>


@endSection






@section('additional-js')
    <script src="{{ asset('/dassets/js/jquery.validate.js') }}"></script>
    <!-- Plugins Js -->
    <script src="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/select2/select2.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/multiselect/jquery.multi-select.js') }}"></script>
    <script src="{{ asset('/dassets/libs/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>


    <!-- Init js-->
    <script src="{{ asset('/dassets/js/pages/form-advanced.init.js') }}"></script>


@endSection()

resources/views/orders/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Order List')

@section('additional-css')
    <link href="{{ asset('/dassets/libs/datatables/dataTables.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/datatables/select.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />

@endSection()



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->

            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Order List</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Order List</h4>
                    </div>
                </div>

                @include('.orders.order-list')


            </div>


        </div> <!-- content -->
    @endSection


    @section('additional-js')

        <!-- datatable js -->
            <script src="{{ asset('/dassets/libs/datatables/jquery.dataTables.min.js') }}"></script>
            <script src="{{ asset('dassets/libs/datatables/dataTables.bootstrap4.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/dataTables.responsive.min.js') }}"></script>
            <script src="{{ asset('/assets/libs/datatables/responsive.bootstrap4.min.js') }}"></script>

            <script src="{{ asset('/dassets/libs/datatables/dataTables.buttons.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.bootstrap4.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.html5.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.flash.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/buttons.print.min.js') }}"></script>

            <script src="{{ asset('/dassets/libs/datatables/dataTables.keyTable.min.js') }}"></script>
            <script src="{{ asset('/dassets/libs/datatables/dataTables.select.min.js') }}"></script>



            <!-- Datatables init -->
            <script src="{{ asset('/dassets/js/pages/datatables.init.js') }}"></script>
            <script src="{{ asset('dassets/js/pages/form-advanced.init.js') }}"></script>

@endSection

resources/views/orders/order-list.blade.php
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if($orders->isEmpty())
                    <h4 class="text-center">There are currently no <strong>Orders</strong> in the system</h4>
                    @else
                    <table id="basic-datatable" class="table dt-responsive nowrap">
                        <thead>
                        <tr>
                            <th>Order Number</th>
                            <th>Date Created</th>
                            <th>Order Status</th>
                            <th>Manage</th>
                        </tr>
                        </thead>


                        <tbody>

                        @foreach($orders as $order)

                            <tr>
                                <td>{{ $order->order_number }}</td>
                                <td>{{ $order->created_at }}</td>
                                <td>
                                    @if($order->status == 'Pending')
                                        <span class="badge badge-soft-warning py-1">{{ $order->status }}</span>
                                    @elseif ($order->status == 'Cancelled')
                                        <span class="badge badge-soft-danger py-1">{{ $order->status }}</span>
                                    @elseif ($order->status == 'Approved')
                                        <span class="badge badge-soft-success py-1">{{ $order->status }}</span>
                                        @else
                                        <span class="badge badge-soft-warning py-1">{{ $order->status }}</span>
                                    @endif
                                </td>
                                <td class="text-center"> <a href="{{ route('orders.show', $order->order_number ) }}" class="btn btn-outline-primary btn-block btn-group-lg">Manage Order</a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif

            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>

resources/views/orders/show.blade.php
@extends('layouts.dashboard')
@section('title', 'Manage Order')

@section('additional-css')
    <link href="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" rel="stylesheet"  type="text/css" />
    <link href="{{ asset('/dassets/libs/select2/select2.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('dassets/libs/multiselect/multi-select.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/flatpickr/flatpickr.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.css') }}" rel="stylesheet" type="text/css"/>
@endSection



@section('content')
    <div class="content">

        <!-- Start Content-->
        <div div class="content">

            <!-- Start Content-->
            <div class="container-fluid">
                <div class="row page-title">
                    <div class="col-md-12">
                        <nav aria-label="breadcrumb" class="float-right mt-1">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">{{ $projectName }}</a></li>
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Update Order</li>
                            </ol>
                        </nav>
                        <h4 class="mb-1 mt-0">Manage Order</h4>
                    </div>
                </div>
                @include('layouts.includes.success')
                @include('layouts.includes.errors')
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="header-title mt-0 mb-1">Update Order</h4>
                                <p class="sub-header"></p>
                                <form action="{{ route('orders.update', $orderDetails[0]->order_number)  }}" method="post">
                                    {{ csrf_field() }}

                                    {{ method_field('PATCH') }}

                                    <div class="form-group">
                                        <label>Change Status</label>
                                        <select name="status" class="form-control">
                                            <option value="" selected disabled hidden>Status</option>
                                             <option value="Approved">Approved</option>
                                             <option value="Pending">Pending</option>
                                             <option value="Cancelled">Cancelled</option>
                                       </select>
                                     </div>

                                    <div class="form-group row">
                                        <div class="col-lg-6">
                                            <a href="#" class="btn btn-block btn--md btn-danger" onclick="goBack()">Cancel</a>
                                        </div>
                                        <div class="col-lg-6">
                                            <button class="btn btn-block btn--md btn-primary" type="submit">Update Order</button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>


                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                @if($orderDetails->toArray())
                                    <table id="basic-datatable" class="table dt-responsive nowrap">
                                        <thead>
                                        <tr>
                                            <th>Order Number</th>
                                            <th>Item</th>
                                            <th>Size</th>
                                            <th>Details</th>
                                            <th>Qty</th>
                                            <th>Total</th>
                                            <th>Payment</th>

                                        </tr>
                                        </thead>


                                        <tbody>
                                        @foreach($orderDetails as $details)
                                            <tr>
                                                <td>{{$details->order_number }}</td>
                                                <td>{{$details->title }}</td>
                                                <td>{{$details->size }}</td>
                                                <td>{{$details->details }}</td>
                                                <td>{{$details->quantity }}</td>
                                                <td>{{$details->total }}</td>
                                                <td>{{$details->payment_method }}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                @endif

                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->

                </div>


            </div>
        </div>
    </div>


@endSection






@section('additional-js')
    <script src="{{ asset('/dassets/js/jquery.validate.js') }}"></script>
    <!-- Plugins Js -->
    <script src="{{ asset('/dassets/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/select2/select2.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/multiselect/jquery.multi-select.js') }}"></script>
    <script src="{{ asset('/dassets/libs/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') }}"></script>
    <script src="{{ asset('/dassets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>


    <!-- Init js-->
    <script src="{{ asset('/dassets/js/pages/form-advanced.init.js') }}"></script>


@endSection()